### ISSUE TITLE
Unexpected behaviour: multiple replies to one request message

### ISSUE THREAD

**Issue by ZiluTian** [ZiluTian/economic_simulations#26]
In Actor.addReceiveMessages(), 

Error message: 
```
Exception in thread "main" java.util.NoSuchElementException: key not found: 779a1152-6498-467b-853d-58179c84cd41
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:63)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
	at meta.deep.runtime.Actor.$anonfun$addReceiveMessages$3(Actor.scala:267)
	at meta.deep.runtime.Actor.$anonfun$addReceiveMessages$3$adapted(Actor.scala:266)
```

Traces show that certain messages are replied multiple times, though only requested once; as seen in Turn 8 below
```
(Time 0.0 Turn 0)
Send async msg1 2
Send async msg1 3
Send async msg1 4
Send async msg1 5
Send async msg1 6
(Time 0.0 Turn 1)
Async msg received from 6
msg not completed! 2
msg not completed! 3
msg not completed! 4
msg not completed! 5
msg not completed! 6
(Time 0.0 Turn 2)
Reply to: 6
Async msg received from 4
msg not completed! 2
msg not completed! 3
msg not completed! 4
msg not completed! 5
msg not completed! 6
(Time 0.0 Turn 3)
Reply to: 4
Async msg received from 5
msg not completed! 2
msg not completed! 3
msg not completed! 4
msg not completed! 5
Response received 500 Id: 6
(Time 0.0 Turn 4)
Reply to: 5
Async msg received from 3
msg not completed! 2
msg not completed! 3
Response received 500 Id: 4
msg not completed! 5
Send async msg1 6
(Time 0.0 Turn 5)
Async msg received from 6
msg not completed! 2
msg not completed! 3
Send async msg1 4
Response received 500 Id: 5
msg not completed! 6
(Time 0.0 Turn 6)
Async msg received from 4
msg not completed! 2
msg not completed! 3
msg not completed! 4
Send async msg1 5
msg not completed! 6
(Time 0.0 Turn 7)
Async msg received from 5
msg not completed! 2
msg not completed! 3
msg not completed! 4
msg not completed! 5
msg not completed! 6
(Time 0.0 Turn 8)
Reply to: 5
Reply to: 5
Reply to: 5
Reply to: 3
Async msg received from 2
msg not completed! 2
msg not completed! 3
msg not completed! 4
msg not completed! 5
msg not completed! 6
(Time 0.0 Turn 9)
Reply to: 2
msg not completed! 2
Response received 500 Id: 3
```

**Comment by ZiluTian** [comment]
Caused by nested wait statements; the above trace is from nb_methods_example, the waitTurns(1) inside the nb_methods_example.object2.get(). The bug is because of the implicit handleMsg in each wait statement. Separate out the handleMessage fixed the issue.
